# kuma control plane that includes Namespace, Deployments, Services

apiVersion: v1
kind: Namespace
metadata:
  name: kuma-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-control-plane
  namespace: kuma-system
  labels:
    app: kuma-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma-control-plane
  template:
    metadata:
      labels:
        app: kuma-control-plane
    spec:
      containers:
        - name: kuma-control-plane
          image: kong-docker-kuma-docker.bintray.io/kuma-cp:latest
          ports:
            - containerPort: 5681
              name: kuma-cp-api
            - containerPort: 5682
              name: kuma-cp-web
          env:
            - name: KUMA_MODE
              value: "standalone"
            - name: KUMA_STORE_TYPE
              value: "kubernetes"

---
apiVersion: v1
kind: Service
metadata:
  name: kuma-control-plane
  namespace: kuma-system
  labels:
    app: kuma-control-plane
spec:
  ports:
    - port: 5681
      name: kuma-cp-api
    - port: 5682
      name: kuma-cp-web
  selector:
    app: kuma-control-plane